# Setup
This section downloads code, data and installs needed dependencies

In [ ]:
! pip install pyod

In [ ]:
import pandas as pd

In [1]:
from data_loading import load_wine

In [ ]:
from pyod.models.cblof import CBLOF

# Anomaly detection flows

C:\Users\Asia\PycharmProjects\anomaly-detection\venv\lib\site-packages\pyod\models\cblof.py:253: UserWarning: The chosen clustering for CBLOF does not havethe center of clusters. Calculate the centeras the mean of the clusters.
  warnings.warn("The chosen clustering for CBLOF does not have"


array([0, 0, 0, ..., 0, 0, 0])

array([ 5.60974975,  5.33420575, 25.61337545, ..., 21.05396548,
       25.81856662, 15.13885745])

In [13]:
from sklearn.metrics import roc_auc_score, f1_score, precision_score, recall_score

def score( y_true, y_pred, y_proba):
    recall = recall_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    roc = roc_auc_score(y_true, y_proba)
    f1 = f1_score(y_true, y_pred)
    print(f"F1: {f1}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"ROC AUC: {roc}")
    return [precision, recall, f1, roc]

F1: 0.016666666666666666
Precision: 0.012578616352201259
Recall: 0.024691358024691357
ROC AUC: 0.5341661380308723


In [2]:
import numpy as np

array([-1], dtype=int64)

In [ ]:
from clustering import ClusterBasedAnomalyDetection
from wrappers import DBSCANWrapped
from sklearn.cluster import DBSCAN


X, y = load_wine("../data/raw/wine/winequality-red.csv")
dbscan = DBSCAN(eps = 3, min_samples=1)
w = DBSCANWrapped(dbscan)
cbad = ClusterBasedAnomalyDetection(clustering_estimator=w, dissimilarity_measure="cblof")
res = cbad.detect(X)

In [ ]:
res

In [7]:
from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps = 3, min_samples=1)

dbscan

DBSCAN(eps=3, min_samples=1)

In [10]:
X, y = load_wine("../data/raw/wine/winequality-red.csv")

dbscan.fit(X)
dbscan.labels_

array([  0,   0,   0, ..., 200,   0,   0], dtype=int64)

In [26]:
from wrappers import DBSCANWrapped

w = DBSCANWrapped(dbscan)

In [ ]:
w.labels_

In [ ]:
dbscan.fit(X

In [21]:
clf_d = CBLOF(alpha=0.9, beta=5, clustering_estimator=w)
res_d = clf_d.fit(X)

ValueError: 'list' argument must have no negative elements

In [22]:
np.unique(clf_d.cluster_labels_)


array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16], dtype=int64)

In [ ]:
# dbscan
clf =

# Hyperparameters tuning

# Experiments
## Experiment 1 - Dissimilarity measure comparison

## Experiment 2 - Comparison with One-class classification